[tools]
node = "lts"
python = "latest"
uv = "latest"
pipx = "latest"
dotnet = "latest"
terraform = "latest"

# npm
"npm:pnpm" = "latest"
"npm:@antfu/ni" = "latest"

# Shell
"ubi:rossmacarthur/sheldon" = "latest"
"ubi:Ryooooooga/zabrze" = "latest"
usage = "latest"
starship = "latest"
lsd = "latest"
fzf = "latest"

# Tools
"pipx:mineru" = { version = "latest", extras = "core" }
"pipx:plamo-translate" = "latest"
"npm:@google/gemini-cli" = "latest"
"npm:@openai/codex" = "latest"

[settings]
experimental = true
python.uv_venv_auto = true
idiomatic_version_file_enable_tools = ["rust", "python"]
