[tools]
node = "lts"
bun = "latest"
deno = "latest"
dotnet = "latest"
go = "latest"
python = "latest"
uv = "latest"
pipx = "latest"
terraform = "latest"

# npm
"pnpm" = "latest"
"yarn" = "latest"
"npm:@antfu/ni" = "latest"

# Shell
"github:rossmacarthur/sheldon" = "latest"
"github:Ryooooooga/zabrze" = "latest"
lazygit = "latest"
starship = "latest"
lsd = "latest"
fzf = "latest"
bat = "latest"
ripgrep = "latest"
zellij = "latest"
difftastic = "latest"
hyperfine = "latest"
1password = "latest"
cargo-binstall = "latest"
"cargo:mergiraf" = "latest"

# Tools
codex = "latest"
claude = "latest"
gemini = "latest"
opencode = "latest"

[settings]
experimental = true
npm.package_manager = "bun"
python.uv_venv_auto = true
idiomatic_version_file_enable_tools = ["rust", "python", "node"]
