[tools]
node = "lts"
bun = "latest"
deno = "latest"
python = "latest"
dotnet = "latest"
uv = "latest"
pipx = "latest"
terraform = "latest"

# npm
"npm:pnpm" = "latest"
"npm:yarn" = "latest"
"npm:@antfu/ni" = "latest"

# Shell
"github:rossmacarthur/sheldon" = "latest"
"github:Ryooooooga/zabrze" = "latest"
"github:jesseduffield/lazygit" = "latest"
usage = "latest"
starship = "latest"
lsd = "latest"
fzf = "latest"
bat = "latest"
ripgrep = "latest"

# Tools
"pipx:mineru" = { version = "latest", extras = "core" }
"pipx:plamo-translate" = "latest"
"npm:@google/gemini-cli" = "latest"
"npm:@openai/codex" = "latest"
"aqua:suzuki-shunsuke/pinact" = "latest"

[settings]
experimental = true
python.uv_venv_auto = true
idiomatic_version_file_enable_tools = ["rust", "python", "node"]
