[tools]
node = "lts"
bun = "latest"
deno = "latest"
python = "latest"
dotnet = "latest"
uv = "latest"
pipx = "latest"
terraform = "latest"

# npm
"npm:pnpm" = "latest"
"npm:yarn" = "latest"
"npm:@antfu/ni" = "latest"

# Shell
"github:rossmacarthur/sheldon" = "latest"
"github:Ryooooooga/zabrze" = "latest"
lazygit = "latest"
starship = "latest"
lsd = "latest"
fzf = "latest"
bat = "latest"
ripgrep = "latest"
difftastic = "latest"
1password = "latest"

# Tools
codex = "latest"
claude = "latest"
gemini = "latest"
opencode = "latest"

[settings]
experimental = true
python.uv_venv_auto = true
idiomatic_version_file_enable_tools = ["rust", "python", "node"]
